image: arkye/stiltzkey-cicd:latest
services:
  - docker:dind
stages:
  - test
  - push image
  - deploy

# Stage: test
test:
  stage: test
  script:
    - docker-compose -f ./docker-compose.test.yml run --rm phoenix
  tags:
    - docker

# Stage: push image
push staging image:
  stage: push image
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker-compose -f ./docker-compose.build.staging.yml build
    - docker-compose -f ./docker-compose.build.staging.yml push
  only:
    - /develop/
  tags:
    - docker

push production image:
  stage: push image
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker-compose -f ./docker-compose.build.production.yml build
    - docker-compose -f ./docker-compose.build.production.yml push
  only:
    - /master/
  tags:
    - docker

# Stage: deploy
deploy staging:
  stage: deploy
  environment: staging
  script:
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service phoenix --no-finish-upgrade
  only:
    - /develop/
  tags:
    - docker

# Not yet on production
# deploy production:
#   stage: deploy
#   environment: production
#   script:
#     - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service phoenix --no-finish-upgrade
#   only:
#     - /master/
#   tags:
#     - docker
