version: '2'

services:
  phoenix:
    image: arkye/stiltzkey:latest
    depends_on:
      - postgres
    environment:
      CIPHER_KEYPHRASE: stiltzkeyprodkeyphrase
      CIPHER_IVPHRASE: stiltzkeyprodivphrase
      CIPHER_MAGIC_TOKEN: stiltzkeyprodmagictoken
      GUARDIAN_SECRET_KEY: HNinpKh9Ne3tr8BpjCpAEh0xzCqTIG3PWsfkR2AtzvUaRIpbs6oIQ9RcmjmGPekJ
      HOSTNAME: example.com
      MIX_ENV: prod
      POOL_SIZE: 15
      PORT: 80
      POSTGRES_DATABASE: stiltzkey
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: stiltzkey
      POSTGRES_USER: stiltzkey
      SECRET_KEY_BASE: 6JlioTCLygI6FfeatExSxXFRHQGFi4Q2XGAGQ8AGQPywZJMfIrJErk55c7FeG5cX
    ports:
      - 80:80
    restart: unless-stopped

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: stiltzkey
      POSTGRES_PASSWORD: stiltzkey
    restart: unless-stopped
    volumes:
      - /path/to/postgres:/var/lib/postgresql/data
